### ISSUE TITLE
Take advantage of MultiSlice on StorageProxy

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#104]
See description in:
https://issues.apache.org/jira/browse/CASSANDRA-3885

This does not appear to be exposed in the API yet, so we could take advantage of this.

**Comment by edwardcapriolo** [comment]
Seems to be an easy win.

**Comment by zznate** [comment]
A little more involved than I thought initially, but still do-able. Needs to be done thusly:
- create an array of ColumnSlice objects accordingly
- construct SliceQueryFilter with a ColumnSlices array
- use that SliceQueryFilter to construct a SliceFromReadCommand
- send that SliceFromReadCommand to StorageProxy#fetchRows

**Comment by edwardcapriolo** [comment]
I added this to core cassandra it is part of the 3.0...thats right I said 3.0 branch...what a joke.
