### ISSUE TITLE
OperationsRequestHandler has a bunch of instance variables

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#111]
We need to make this class re-entrant - looks like all the other classes are correct though.

**Comment by edwardcapriolo** [comment]
That was probably my fault it was a private class I moved as part of a code cleanup. Was not sure if the move was correct or not.

**Comment by zznate** [comment]
This actually works for now given that the OperationsRequestHandler is itself created via "new" within the Handle method of IntraHandlerJson. 

We'll leave this open though as it would benefit us to not create a new object on each hit.

**Comment by edwardcapriolo** [comment]
now that we have made some aggressive changes I think the time to fix is
now.

**Comment by jsanda** [comment]
Yeah since OperationsRequestHandler executes operations serially,
reentrancy is not an issue at the moment, but once we start supporting
executing operations in parallel, it will have to change. With respect to
creating new instances the class maintains some request state. Maybe we
need to move that state into IntraState or vice-versa.

On Mon, Feb 25, 2013 at 6:22 PM, edwardcapriolo notifications@github.comwrote:

> now that we have made some aggressive changes I think the time to fix is
> now.
> 
> On Monday, February 25, 2013, Nate McCall notifications@github.com
> wrote:
> 
> > This actually works for now given that the OperationsRequestHandler is
> > itself created via "new" within the Handle method of IntraHandlerJson.
> > 
> > We'll leave this open though as it would benefit us to not create a new
> > object on each hit.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zznate/intravert-ug/issues/111#issuecomment-14082867
> .

## 
- John

**Comment by jsanda** [comment]
To further clarify about the object creation, as I worked in the
async-requests branch, I was not using IntraReq, IntraRes, and IntraState.
I wound up creating JsonObjects with the minimal fields/properties
necessary. In the sync version of the request processing where request
handling went through IntraService, we created a IntraState object for each
request. In the async version, we are creating an OperationsRequestHandler
for each request but we are not creating an IntraState object. I wanted to
point out that distinction. As more of the operations are ported it might
make sense look at moving the state in OperationsRequestHandler into
IntraState. Some of that state is used to determine which operation to
execute next and whether or not more operations are left to execute. I
haven't thought enough about it yet.

On Mon, Feb 25, 2013 at 6:35 PM, John Sanda john.sanda@gmail.com wrote:

> Yeah since OperationsRequestHandler executes operations serially,
> reentrancy is not an issue at the moment, but once we start supporting
> executing operations in parallel, it will have to change. With respect to
> creating new instances the class maintains some request state. Maybe we
> need to move that state into IntraState or vice-versa.
> 
> On Mon, Feb 25, 2013 at 6:22 PM, edwardcapriolo notifications@github.comwrote:
> 
> > now that we have made some aggressive changes I think the time to fix is
> > now.
> > 
> > On Monday, February 25, 2013, Nate McCall notifications@github.com
> > wrote:
> > 
> > > This actually works for now given that the OperationsRequestHandler is
> > > itself created via "new" within the Handle method of IntraHandlerJson.
> > > 
> > > We'll leave this open though as it would benefit us to not create a new
> > > object on each hit.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/zznate/intravert-ug/issues/111#issuecomment-14082867
> > .
> 
> ## 
> - John

## 
- John

**Comment by zznate** [comment]
I would like to move past an initial 'parse phase' from the jsonObject and use IntraReq|Res|State.

This goes back to our original discussion - maybe we 'extend' JsonObject with some stronger typing around the map-i-ness of it. 

Thoughts?

**Comment by jsanda** [comment]
Extending JsonObject is exactly what I had in mind.

On Mon, Feb 25, 2013 at 7:21 PM, Nate McCall notifications@github.comwrote:

> I would like to move past an initial 'parse phase' from the jsonObject and
> use IntraReq|Res|State.
> 
> This goes back to our original discussion - maybe we 'extend' JsonObject
> with some stronger typing around the map-i-ness of it.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zznate/intravert-ug/issues/111#issuecomment-14085150
> .

## 
- John

**Comment by edwardcapriolo** [comment]
So I am trying to developer the service processor interface again and I am thinking this re-entrant code is what is missing me up. So something I do not understand, wouln't it be easier of OperationsRequestHandler was just a while loop, that executed each op like the original code was?

**Comment by jsanda** [comment]
Not sure if it that could even work. Each operation is a handler that
receives requests on the event bus and sends responses on the event bus.
Whether it is OperationsHandler or something else, there needs to be a
handler to process those responses coming back on the bus. I think in order
to make things work by putting it in a while loop would require processing
everything synchronously, or at least those operations you want to do in
the loop. If you do want to pursue processing synchronously, then I'd
suggest look at moving stuff into a worker verticle so that event loop
threads aren't tied up.

On Fri, Mar 8, 2013 at 9:00 PM, edwardcapriolo notifications@github.comwrote:

> So I am trying to developer the service processor interface again and I am
> thinking this re-entrant code is what is missing me up. So something I do
> not understand, wouln't it be easier of OperationsRequestHandler was just a
> while loop, that executed each op like the original code was?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zznate/intravert-ug/issues/111#issuecomment-14655962
> .

## 
- John

**Comment by edwardcapriolo** [comment]
Good point I see that the handler has to receive the events, but I am a but confused how the interation happens maybe it is unrealted to the issues that I am having

**Comment by edwardcapriolo** [comment]
I am going to close this. ATM I see some different ways to do this but we dont have anything on the table other then a re-entrant handler which works well evnough for the moment. If someone has a concrete idea they are looking to implement they can re-open.
