### ISSUE TITLE
Add some static utilities for common handler operations

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#112]
There are a lot of operations within the new Handler impls that are similar-ish enough to live in a utility class. E.g. 

```
    Integer id = event.body.getInteger("id");
    JsonObject params = event.body.getObject("op");
    JsonObject state = event.body.getObject("state");
```

Create a utility class to two for encapsulation of such.

**Comment by edwardcapriolo** [comment]
I think we should really focus on just using JSONObject right from the client and not use jackson anymore .

**Comment by zznate** [comment]
Yep - my goal with this issue was simply to get to a point where we alleviate any dupped code.
