### ISSUE TITLE
Create handlers for filter ops

### ISSUE THREAD

**Issue by jsanda** [zznate/intravert-ug#115]
Need to create operation handlers for CREATEFILTER, FILTERMODE, and also implement logic for executing a filter and returning the filtered results.

**Comment by jsanda** [comment]
I pushed an initial set of changes at https://github.com/jsanda/intravert-ug/tree/filter-handler. The integration test for column slice filters passes. I need to implement support in GetHandler yet. Then I need to see what can be done to reduce the excessive JsonObject creation and mapping back and forth.

**Comment by edwardcapriolo** [comment]
Seemslike this is done.
