### ISSUE TITLE
Create Handler for BatchSet operation

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#118]
Import handler from InterOp for batch set. Add JSON test cases for such.

**Comment by edwardcapriolo** [comment]
When the code was ported there was an method

getkeyspace(Row, op, state)

This was wrongly changed to

getkeysapce(op,state)

This is why the batch test is failing.. Each row can have its own keyspace. This was true in many places and needs to be added back to the code

**Comment by edwardcapriolo** [comment]
See this page.

https://github.com/zznate/intravert-ug/wiki/MultiBatches-batches-across-multiple-keyspaces
