### ISSUE TITLE
Update json-smile endpoint to be async

### ISSUE THREAD

**Issue by jsanda** [zznate/intravert-ug#135]
IntraHandlerJsonSmile still delegates request processing to IntraService.handleIntraReq. It needs to be refactored to delegate request/operation processing to handlers via the event bus.

**Comment by edwardcapriolo** [comment]
Theoretically the json and json smile endpoint can be refactored one class with two instance , a constructor arg can pass in the jackson mapper, smiled or unsmiled

**Comment by edwardcapriolo** [comment]
Was removed. reopen if you wantto add it back.
