### ISSUE TITLE
Handle Jackson mapping errors in json-smile endpoint

### ISSUE THREAD

**Issue by jsanda** [zznate/intravert-ug#136]
Right now if a Jackson exception is thrown in IntraHandlerJsonSmile we are swallowing the exceptions. There needs to be error handling like what was added in IntraHandlerJson in commit 41c2f72. Ideally the endpoints should do at little work as possible and delegate to common, shared, internal request handling code.

**Comment by edwardcapriolo** [comment]
I removed the smile endpoint because it was broken and out of sync.
