### ISSUE TITLE
Move refactor IntraHandlerJson to extend IntraHandlerBase

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#142]
This involves several parts:
- moving IntraHandlerJson into handler.http.payload package
- moving new IntraHandlerRest into handler.http.rest package
- moving up the functionality as needed for IntraHandlerJson to be in the new IntraHandler hierarchy
- changing the bus names to be more reflective of this split. eg.: "request._" gets changed to "http.payload._" and we introduce a "http.rest.*" 

This last part gives us a cleaner uniformity to bus identifiers and package names which just feels like good practice to me.

**Comment by edwardcapriolo** [comment]
Realted question.

  logger.debug("Starting IntravertCassandraServer...");
    vertx = Vertx.newVertx();
    rm = new RouteMatcher();
    rm.put("/:appid/hello", new HelloHandler());
    rm.get("/:appid/hello", new HelloHandler());
    rm.post("/:appid/hello", new HelloHandler());
    rm.post("/:appid/intrareq-json", new IntraHandlerJson(vertx));
    rm.post("/:appid/intrareq-jsonsmile", new IntraHandlerJsonSmile(vertx));

I copied the appid convention from the original script what is this? why are we doing this ? should we change this?

**Comment by edwardcapriolo** [comment]
Also we may want to take care of versioning here. For both the html endpoints and the handler names. If we make breaking changes we should bump versions and consider supporting old code for at least 2 majors.

**Comment by zznate** [comment]
I will take 'appid' out with this issue as well. This was from the original usergrid use case. I'll have this one cleaned up today.
Agreed on the versioning. But that is more sophisticated than it seems (the way I want to do it - both pragamatically and rest-full-y) that I'll open another ticket.

**Comment by zznate** [comment]
Added #148 for tracking versioning.

**Comment by zznate** [comment]
Created #157 for tracking removal of appid

**Comment by edwardcapriolo** [comment]
Are we done here?
