### ISSUE TITLE
Add hypermedia to the REST API.

### ISSUE THREAD

**Issue by boneill42** [zznate/intravert-ug#144]
Just starting the thread to brainstorm what a hyper media API looks like for Cassandra, and how we might implement it.

What do you think the best approach is to add hypermedia to the REST API?

Do we create a new handler?  or add to the existing "virgil port"?

How do we "go hyper"?  If I hit the base url for myapp, do I get back a list of urls, one per keyspace? (essentially, the hypermedia version of a "describe keyspaces")

Likewise, if I then follow those "keyspace urls", I would get back the results of a describe tables?

What then, if I follow a url for a specificl column family?  statistics for that column family?

**Comment by zznate** [comment]
A lot of this will depend on the security model stuff - particularly issue #36. 

But yes, i like the idea described above up to the column family endpoints. Not sure what to do there as we cant really go dump keys and such.

**Comment by boneill42** [comment]
RE: dumping keys
Agreed, maybe we could dump ranges or something that would enable paging.   It would be wicked cool if we dump the actual links a javascript UI could then use.  (i.e. allow people to specify "page size" in the initial request)

**Comment by zznate** [comment]
... thats interesting. The pre-canned slice points for ranging over the CF?

**Comment by boneill42** [comment]
xactly. (or row)

**Comment by zznate** [comment]
Those queries would be f*ing gnarly, but that is ultra compelling as a feature.
