### ISSUE TITLE
Base class for handlers

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#174]
Handlers need a base class that can deal with runtime exceptions.

**Comment by zznate** [comment]
This should probably be done before work starts on #162 (which should probably have this plumbing in place to make things easier). Thus, #161 is tangentially relevant as well.

**Comment by edwardcapriolo** [comment]
#161 and #162 both tangential. This feature should do one critical thing.
1) ensure that any exception the handler throws is caught.

As a side effect it should/probably will make it easier to unit test the logic of a handler.

For a follow up we will be able to add yammer to this base class for performance tracking.

**Comment by edwardcapriolo** [comment]
So I coded up a simple base class called AbstractHandler. https://github.com/zznate/intravert-ug/tree/abstract_handler . Please supply some comments.

**Comment by zznate** [comment]
This looks fine - I did something similar in for http - see o.u.v.handler.IntraHandlerBase. 

I think we need to have better naming scheme for http vs. msg bus handlers and push that into the packages. 

Having good/predictable package and class names will make it easy for people hacking around to get started.

**Comment by edwardcapriolo** [comment]
This is done. We can convert invidual handlers as we touch them
