### ISSUE TITLE
Transport Architecture: Load balancing

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#2]
Review best of breed from hector, astyanax and twitter's finnagle. This task is to document the architecture which should be composed of at least initially:
- round robin by default
- client-mediated selects/mutates (send to owner replica)
- composable policies (latency aware wraps round robin)
- data center awareness
- modify host lists based on messages received from cassandra cluster

**Comment by jancona** [comment]
You'll probably want a least active policy too. When using round robin (in Hector), we saw lots of requests backing up against a slow node, to the point that the pool is exhausted. Least active seemed much better behaved.

**Comment by zznate** [comment]
We are actually punting completely on the client for now and focusing on the transport architecture as there are a number of libraries/techniques/etc for load balancing HTTP (i've been impressed with Twitter's Finnagle as a library [though build is cumbersome-ish]).
