### ISSUE TITLE
Rename ServiceProcessor to Procedure

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#208]
Filter is a good name, processor is a good name, multi-processor is an ok name. But ServiceProcessor is just one to many components named Xprocessor and not very descriptive. I think we should just rename it to Procedure or possibly trigger (in the code and the documentation) (

@doellerbe might want to tackle this.

**Comment by zznate** [comment]
Procedure is good - we should avoid trigger so as not to confuse folks with cassandra impl.

**Comment by edwardcapriolo** [comment]
Well thats their problem our was done first :)
