### ISSUE TITLE
Remove vertx return to thread pool/blocking web application model

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#214]
The plan here is:
1) tag
2) pretty much clean out the project and start fresh
3) repackage as io.teknek.intravert
4) produce maven artifact
5) re implement features as close as possible to original intravert json protocol (features may be modified/removed)

We learned a lot with vertx and we learned from CQL. I look at what influxdb.org is doing and think that the majority of these things can be handled by intravert's original mission triggers and enhanced server side capabilities. Cassandra proper is not very open to be turning complete so intravert's mission could live on.

**Comment by zznate** [comment]
SGTM. I want to make sure that "thread pool/blocking" model part is encapsulated. Eg. "BlockingIntravertServer" and "NIOIntravertServer" (or whatev) both implement "IntravertServer."

Though I agree completely with starting on the non-blocking one to minimize the moving parts.

**Comment by edwardcapriolo** [comment]
Also going to base the initial cut off 1.2.X since 2.0.x was a series of releases that I do not think got wide adoption over the actual user base

**Comment by edwardcapriolo** [comment]
@zznate Please review and comment on
https://github.com/zznate/intravert-ug/compare/freshstart?expand=1

As you can see we have gone back to a simple model. A web server (probably jetty) will sit on top of DefaultIntravertService. It will accept json serialized Request objects and Respond with json serialization response objects. There are only minor changes to the intravert wire format. The only thing left in this code is that it should use a tll cache like guava's loading cache to handle sessions.

**Comment by zznate** [comment]
I like this simple model.

I think ApplicationContext would make more sense scoped to the instance of the Action though. Ie. that an Action had to be created with an ApplicationContext. This also implies:
- `ApplicationContext` is immutable for an instance of an Action (this let's us keep Application instances around to be re-used)
- `Operator` and `RequestContext` provided to `Action#doAction` are considered immutable within the scope of a request
- `Response` is appended to (like it is now basically)

Which looks like might largely be your intent.

**Comment by edwardcapriolo** [comment]
ApplicationContext will be like a webapplication context in tomcat. it will hold resources shared across the users.  It is a mutable application wide singleton. 
Only appending to response is too limited. We have operations like `clear` that can wipe out results we do not want to return to the client.

**Comment by edwardcapriolo** [comment]
Check the branch again ... added jetty

**Comment by edwardcapriolo** [comment]
Resolved the new simple jetty system is merged to master
