### ISSUE TITLE
Batching implementation

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#28]
Currently none of our writes batch. I am thinking that we can write two batching verbs batchopen and batchrun:

Op:batchopen
Op:set
Op:get
Op:Getref
Op:set
Opbatchrun

The challenge is the get and getrefs in the middle, would this become batchmutate/ get/ batchmutate?

**Comment by zznate** [comment]
If the getref is implicit on previous operations having been executed, then we cannot leave the mutation open. This should be validatible on the client since we have op numbers. We should throw a syntax/validation error if this is the case.

**Comment by edwardcapriolo** [comment]
Agreed. batches should only have set/mutates. It might be harder to catch client side, and we must check for it server side if we create the syntax this way. Or we could just make a batchmutate verb rather then two verbs. Then we do not have this issue at all.
