### ISSUE TITLE
Add security framework to endpoints

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#36]
Using Apache Shiro would be the best bet. 

I see two aspects to this within the context of how vertx and cassandra integration will shake out
1. the obvious REST case of securing access to the endpoints
2. less obvious case (to me anyway) of locking down the websocket channel which we'll use to communicate cluster state/changes back out to the client

Per point [1], I'd like this to be flexible enough to able to do things like allow world+dog access to specific operations on specific keyspace and/or column family operations with something like "allow all GETs on mykeyspace and mycolumnfamily." This way, for some use cases, folks could just park the cluster behind a load balancer and let the javascript crowd go nuts with something like: 
GET /mykeyspace/mycolumn_family/mykey

**Comment by tnine** [comment]
Has anyone given any thought on how we boostrap permissions for an admin role?  Properties, then users can go from there?  What about registration, tokens etc?  I'm assuming that we want to try to get some basic OAuth functionality in this to allow 3rd party access?

**Comment by zznate** [comment]
There is already an OAuth vert.x module in the modules repository, but I have not looked at it in detail yet. 

Per the bootstrapping question, I would just sit this on top of the default shiro functionality for an .ini provider as detailed here: http://www.infoq.com/articles/apache-shiro

**Comment by zznate** [comment]
To be clear, yes we would want registration and token endpoints as well as some management plumbing. These should probably each be separate issues with the basic URL protection via defaults addressed herein.
