### ISSUE TITLE
foreach verb

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#39]
So there are cases where I would like to do a slice of one column family, then use the value of the slice to do n slices of another column family. 

The syntax would be something like this:
    req.add( IntraOp.sliceOp("rowa", "col1", "z", 4)); //4
        req.add( IntraOp.setcolumnfamilyop("somethingelse") ); //5
        req.add( IntraOp.foreachOp(4, IntraOp.sliceOp( IntraOp.refOp(4,value), "start", "end" ) ) );//6

Does this sound good?

**Comment by zznate** [comment]
In the above example, is the foreachOp necessary?
i.e. given the same first two steps, wouldnt be implied by the (mostly) existing syntax?

``` java
IntraOp.sliceOp( IntraOp.refOp(4), "start", "end" ) ) 
```

**Comment by edwardcapriolo** [comment]
Currently, if you use IntraOp.refOp(4,value) you get -> only element 0 of the get or slice. 

You are correct in saying that we could make the iteration implied, like if we Ref a slice it iterates atomatically and if we Ref a get it does not. 

I will think on that approach but it is a good one.

**Comment by edwardcapriolo** [comment]
There is one challenge of the implicit approach. Currently the Ref operator is resolved inside the resolve(Object) method. So it can not cause iterating logic it can only do one thing, return an object. It can not take control of the processing. Unless we do pre-processing element we wont know if a statement has ref until we hit one.

**Comment by zznate** [comment]
We should have enough information in IntraService#resolveObject to deduce if it is a set of columns, no? Maybe we default to returning a nested map of some sort for a REf regardless of whether its one or more columns.

**Comment by edwardcapriolo** [comment]
The usage is always like this.

private void slice(IntraReq req, IntraRes res, IntraState state,int i){
        IntraOp op = req.getE().get(i);
        List<Map> finalResults = new ArrayList<Map>();
        ByteBuffer rowkey = byteBufferForObject(resolveObject(op.getOp().get("rowkey"),req,res,state,i));

resolveObject IsAlways inside a byteBufferForObject. It does have enough information to deduce if a set will be returned, but it and its caller are not written in a way where it can return this information. 

Also this is going to make any coded that uses code much more complex. set for example is going to turn from a simple function that sets one thing, to a function that could set one thing or n things. So there is going to be lots of duplicate for each detecting code across certain verbs. Essentially each method would need to have (isIterating branches.

I think a cleaner way to do this is let iterate be its own verb, it can set something in the state like an int to explain what element in the list we are currently on. Then resolveObject can leverage this information

```
if (op.getType().equals(IntraOp.Type.GETREF)){
    ...
    if (state.iterating == true){
       int n = state.currentelement
```

Then the iterate verb drives the process of advancing N and calling set/get/slice N times.

I am not 100% in love with this approach. It is really a lispy type 'code is data' problem. But I think introducing the very is rather quick and painless.
...

**Comment by edwardcapriolo** [comment]
By the way nested iterating is impossible, you would only be able to iterate one result. You could then later iterate that if you wanted but iterate ops would never be nested.

**Comment by zznate** [comment]
Could resolveObject check for 'instanceof Iterator.class' as well in this case?

**Comment by edwardcapriolo** [comment]
I think this is too hard to do generically. We will let one of the Processor types handler this. WONTFIX
