### ISSUE TITLE
Transport Architecture: Proxy Base design

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#4]
Base design for client-to-server proxy. This proxy will support:
- cache aggregation 
- large cluster proxy (make a large cluster look like a small one)
  - this implies supporting push-backs from #3
- operation mirroring?

This design should not preclude the proxy running in process with the client

**Comment by edwardcapriolo** [comment]
The "large cluster proxy" is an impedance mismatch with some of our other stated goals. 
1) Being embedded into the Cassandra server
2) sending reads & writes directly to natural endpoint
3) Fundamental load balancing in cassandra
4) caching mentioned as item 1.
Can we support it in a sane way?
