### ISSUE TITLE
timeout & retries

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#41]
Because we are doing multiple operations in on request we need a new concept of timeout. Maybe timeout per op as well as timeout for the entire batch with defaults for both. How should retry be handled especially when using the autotimestamp option?

**Comment by zznate** [comment]
Every op should have it's own timeout type which can use (or extend) GenericTimeoutException or similarly named.

**Comment by edwardcapriolo** [comment]
Timeout has been added in per op. Retries are up to the user.
