### ISSUE TITLE
Support asynchronous long running requests with a webhook callback

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#43]
I see this as having OpType where a 'callback url' is required. 

The execution returns immediately with "OK" and the callback is rung upon completion. 

Not sure yet if this could be a URL or initiated via webhook socket (or options for both).

**Comment by zznate** [comment]
These may really be two different things here - webhook and post-to URL. We'll keep this one issue for the idea of such for now though.

**Comment by edwardcapriolo** [comment]
this is close to my asyc per-op issue. Theoretically this type of thing is built into IntraVert, maybe we can standardize the way to pass data to other verticles/handlers.

**Comment by edwardcapriolo** [comment]
I was thinking the most flexible medium is the JsonObject. So we would converted List<Map> into their json representations and feed them to other verticles/handlers

**Comment by edwardcapriolo** [comment]
When you say "long running" I am guessing you mean in the > c\* RPC time-out range.

We have some challenges to long-running. The first being paging-and the second being memory. A long running request I can picture at this moment would be a huge slice. However a large slice would eventually blow our memory. Now if we had a mechanism to write a slice directly into another column without first buffering it into a result then this feature starts to take shape.

Please give me an example of the long running process you are thinking about.

**Comment by zznate** [comment]
Paged slicing with some sort of transform(s). Think map/reduce light.

**Comment by edwardcapriolo** [comment]
I think we are going to get "Paged slicing with some sort of transform(s). Think map/reduce light." with scanners. The callback hook no. But with scanners the callback could be client side. Do you still want to keep this open?

**Comment by edwardcapriolo** [comment]
I guess there is a case as well for long running scanners that run on the serverside.
