### ISSUE TITLE
Transport Architecture: pluggable cache provider

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#5]
Design the pluggable cache architecture provider similar in function to hibernate's 2nd level cache. Should support multiple libraries and provide for dynamic adjustability (JMX).

**Comment by edwardcapriolo** [comment]
Is this going anywhere? What would we be caching? The output of a handler for a given input? Users can write handler and can write them however they want (with their own cashing theoretically). So do we support this or not and if so how?
