### ISSUE TITLE
Store JSON in column and use a filter to "query" it

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#52]
This would be a pretty powerful example for those that store data in json and want to extract elements server side

**Comment by boneill42** [comment]
Agreed.  We'd love it.

But probably also need to keep in mind that C\* now has native collections.  (we are moving some of our JSON to maps)

**Comment by edwardcapriolo** [comment]
This would be similar to the hive json udf.. More then just collections.

**Comment by edwardcapriolo** [comment]
https://github.com/zznate/intravert-ug/compare/master...json

Branch JSON shows how to use a processor to to JSonPath queries.
