### ISSUE TITLE
What we need for a 1.0 

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#58]
This is an umbrella issue to make a list of some of the things we need for a 1.0 style release.
1) Better timeouts: We can not only rely on C\* timeouts since we are doing things outside of c\* each op should have its own timeout and the entire operation should have a timeout (#41)
2) IntraClient overhaul: The IntraClient is very primitive since it only has one method sendBlocking I thing we can make this a bit cleaner (#77)
3) assume/types: We need cases and test coverage to support all types including composites of all types (#56)
4) install guide on embedding IV into c\* (#78)
5) Scanners (I really want to complete this today)
6) We need some performance benches that test some of our features. In what cases is doing server side jsonpath better then client side parsing, etc, etc. We need some apps that do maybe 10,000 ops the classic way and 10,000 the intravert way and then show how the performance/io/cpu,network is different.
7) timestamps and retries (we do not really have a policy here we need something that makes sence)
8) Security as defined in issue #36 
9) basic REST actions from cassandra-rest/virgil (#6)
10) TTL insert
11) Counters set + get
12) Repackage and general code cleanup

All please pitch in and talk about anything that would make you not want to production-ize intravert at this point

**Comment by zznate** [comment]
I'm still on the hook for install guide (4). Per IntraClient (2), I still feel like this really only needs to be an "example" for now (probably include a non-vertx version as well) that really just shows off the access patterns. 

Given that "the client is HTTP", we have some flexibility here more so than with other transports.

I'm going to add security to the list - that is too easy for critics to pick at and it really won't take long to put something fairly powerful in place.

**Comment by edwardcapriolo** [comment]
Taking a look at out list we have completed most of the objectives.

Coming off the list is anything not done. Meaning
1) security
2) rest
3) scanners
are not 1.0 blockers.

We need left to do is version the endpoints, cleanup class names, use the abstract class to catch errors instead of the handler. Do basic load and fitness testing.

**Comment by edwardcapriolo** [comment]
Reopening
1) making every handler reloadable
2) docs on embedding iv into cassandra
3) docs for running iv as storage proxy
