### ISSUE TITLE
We got groovy, now we need scala,closure, etc

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#59]
The dynamic class loading should take scala, closure, java (local cp), and java (url class loader)

**Comment by zznate** [comment]
Semantics may be different - need to investigate how to get to/work with 'invokeDynamic' in jdk7

**Comment by edwardcapriolo** [comment]
So I have done these buts before for the java case we just send a class name and use the standard class loader. Not the groovy one. For jar the target the arguments would me a main and a list of URLs for url class paths,

I am sure closure and scalla will have a loader similar to the groovy class loader we are using.

**Comment by jsanda** [comment]
I noticed in the examples and tests that create processors it is done via the API by passing embedding the code in a string. This seems like kind of a clunky way to install a processor to perform server-side logic. What if my processor code consists of more than one class, module, namespace (in the case of Clojure), etc. that span multiple files? And what if my processor has some library dependencies?

What about the possibility of packaging and installing the processor as a Vertx verticle or module?

**Comment by zznate** [comment]
Supporting both would be ideal:
1. a simple upload-my-script that we have now (the filter where age > 21 is a legit use case on this, IMO)
2. as you said, jar loading and/or verticle or module

**Comment by zznate** [comment]
Per point 2 above, actually it would be kind of dumb to _not_ leverage what vert.x is quite good at here. 

@jsanda, any thoughts on a design approach?

**Comment by jsanda** [comment]
I'll think about it some and post some ideas later today or tomorrow. I'd
like to flush out some ideas here and then put together a prototype.

On Tue, Feb 5, 2013 at 4:18 PM, Nate McCall notifications@github.comwrote:

> Per point 2 above, actually it would be kind of dumb to _not_ leverage
> what vert.x is quite good at here.
> 
> @jsanda https://github.com/jsanda, any thoughts on a design approach?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zznate/intravert-ug/issues/59#issuecomment-13152360.

## 
- John

**Comment by edwardcapriolo** [comment]
Groovy has an @ GRAB annotation to fetch dependencies and URL classloading requires all libraries to be put on the server. I considered using verticles the issue i found is that calls to other verticles are async. In this case we want this code to run quickly. I am all up for finding another solution but this seemed like the most simple one.

**Comment by edwardcapriolo** [comment]
ALso I do not see filters and other classes being complex. They are mostly small functions with no or few external dependencies.

**Comment by jsanda** [comment]
I know that calls to verticles are done via the event bug and figured that
meant they would be async. Maybe the added latency is ok though. It's hard
for me to say since until I have a better idea of some of the use cases for
a processor/trigger. If you go the route of a Vertx module however, then as
I understand calls are/can be synchronous.

On Tue, Feb 5, 2013 at 4:30 PM, edwardcapriolo notifications@github.comwrote:

> ALso I do not see filters and other classes being complex. They are mostly
> small functions with no or few external dependencies.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zznate/intravert-ug/issues/59#issuecomment-13152973.

## 
- John

**Comment by edwardcapriolo** [comment]
Ok then maybe vertx modules are a better answer. Keep digging around let me know what you find. 

I did my assessment on a few things, EventBus was async. This made it a hard paradigm to use for the filter, processor or multi-processor use case. My use case was simple filters to do pruning or sum. Sending work elsewhere seemed in practical. Another challenge was to do modules right, your supposed to turn everything to json so the modules are cross platform. I did not want to impose async-io + unneeded conversions to do filtering. 

My findings above led me to tackle the problem in it's current manner. I am open to better solutions because I may not have done a 100% correct assessment of what vertx could do, but at this phase I went with something I knew would work.

**Comment by jsanda** [comment]
Looks like my previous comment about module calls being synchronous was wrong. After reviewing the docs and looking at several of the modules at https://github.com/vert-x/vertx-mods I see that everything is still async. Everything goes through the event bus.

I agree for cases where you want to apply a filter, map, reduce, etc. to the result set that it makes more sense to do it synchronously since at that point you already have the results. The service processor example that involves updating an index table and other tasks that could potentially be longer running might make sense to be asynchronous.

**Comment by edwardcapriolo** [comment]
So potentially we can leverage this. But lets just keep it on the back burner for 1.0 stuff here.

> Subject: [vertx:6730] Multi-threaded worker verticles
> To: vertx@googlegroups.com
> 
> This is now done in master.
> 
> As we discussed on other threads, unlike normal worker verticles which
> are never executed concurrently by more than one thread,
> multi-threaded worker verticles can be executed concurrently, e.g. as
> messages are received by event bus handlers they have set.
> 
> They're not really intended for your average application, and you have
> to be careful with them, since you have to make sure the verticle is
> threadsafe unlike others. The use case for them is in writing things
> like database modules where it's awkward implementing these using
> standard worker verticles, since any blocking call on, say, a JDBC api
> would prevent any other messages being received until it had
> completed.
> 
> I would envision that, for example, Tim Yates JDBC module could be
> refactored to be more effective as a multi-threaded worker.

**Comment by edwardcapriolo** [comment]
I recently added closure. Lets close this umbrella. It is vague and not really going anywhere.
