### ISSUE TITLE
eclipse style sheet checked into project

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#61]
Edward is mad ignant yo, he does not know how to setup his tabs etc in eclipse. Can someone make me a style sheet and then I can do one big code cleanup checkin?

**Comment by boneill42** [comment]
I just got setup in Eclipse. It looks like a good bit of the code is 2 space indent.
Is that what we want?  Any other customizations?

We typically start with "Java Convention" in Eclipse, then change it to always use spaces (vs. tabs), and set line width to 120.  What do we want?

Then, where do you want the stylesheet dropped?

**Comment by boneill42** [comment]
Forget it.  Looks like @edwardcapriolo added one to his pull request.

**Comment by boneill42** [comment]
Maybe we should move it out of src/main/resources though? (so it doesn't get bundled into the artfiact)
