### ISSUE TITLE
NPE thrown in IntraOp when ResultMessage.Kind is not ROWS

### ISSUE THREAD

**Issue by jsanda** [zznate/intravert-ug#62]
First let me say, awesome project! I have been poking around in master and it looks like there needs to be a check in IntraOp before iterating over the rows because result.getRows() will be null unless rm.kind == Kind.ROWS. Here is an example using curl to reproduce the exception,

``` bash
curl -H "Content-Type: application/json" -X POST --data @cql.json localhost:8080/:appid/intrareq-json
```

where cql.json looks like,

``` javascript
{"e":[
  {
    "type": "SETKEYSPACE",
    "op": {
      "keyspace": "system"
    }
  },
  {
    "type":"CQLQUERY",
    "op": {
      "version": "3.0.0",
      "query": "CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}"
    }
  }
]}
```

**Comment by edwardcapriolo** [comment]
Right. This makes sense. Not every query will have a result set. Im updating my computer ATM. Will tackle this next since it seems trivial. Thanks for checking us out, this is our first official bug/feature. :) If you have an ideas let us know.

**Comment by edwardcapriolo** [comment]
Resolved in https://github.com/zznate/intravert-ug/pull/63. BTW we would love to have some json/curl/httpclient examples checked into the project, possibly in the form of a unit test.

**Comment by jsanda** [comment]
Sounds good. I'll be working on some.

**Comment by edwardcapriolo** [comment]
I added https://github.com/zznate/intravert-ug/pull/64 for now. This is something we are very interested in. We want intraVert to be the go to client for many cases but the JavaScript/NodeJs async crowd would get the most out of understanding this.
