### ISSUE TITLE
Pick open source licence

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#65]
A wild guess is ApacheV2. All please chime in. We need to put some headers on the source files.

**Comment by jsanda** [comment]
Apache V2 sounds good to me.

**Comment by zznate** [comment]
ASFv2 wfm.

**Comment by edwardcapriolo** [comment]
Ok ASF-v2 it easy. When soeone gets a chance. (sooner is better then later) we should add the notice file and the header to all the appropriate source files.
