### ISSUE TITLE
minor docs issue

### ISSUE THREAD

**Issue by jsanda** [zznate/intravert-ug#66]
The JSON example on https://github.com/zznate/intravert-ug/wiki is wrong. The values for the type field are in lower case but they should be upper case to match the constants in the IntraOp.Type enum. I think the example should look like,

``` javascript
{"e":[
  {"id":1,"type":"CREATEKEYSPACE","op":{"name":"myks","replication":1}},
  {"id":2,"type":"CREATECOLUMNFAMILY","op":{"name":"mycf"}},
]}
```

I am still getting familiar with the code base, but it might  be nice if the type values could be case insensitive.

**Comment by edwardcapriolo** [comment]
That documentation looks somewhat stale at this point. For instance the id is no longer needed. Early on, internally we had a big case statement handling the message routing, but we moved this to the current system and the enum's switched the verb to all caps.

One way this could be easier (for you) is we can put a logging point right at HttpHandler for json. This would dump all the requests inbound and outbound.

Another easy way to do this is to use the Operations class and have jackson give you the json back. 

out.println( mapper.writeValueAsString( Operations.setOp("mkkeyspace") )  );

I think you are aware of this but just to say it, we are pre 1.0. So the format is not set in stone. I did mention wanting more documentation around the json bits but I would not jump in and document the entire thing until we are sure the format is locked down. We have another issue called "what we need for 1.0"

Feel free to edit the wiki. If you do not have access I grant you.

**Comment by edwardcapriolo** [comment]
Please note: We have not had an official 1.0 release. This documentation currently serves as a starting point for developers and users interested in the project. However because we have not had an official release and are actively hacking on the project some of this information might be incorrect. 

I added this comment to the page and fixed any misc issues I found.

**Comment by jsanda** [comment]
I totally understand that things are still fluid, and I appreciate the quick turn around and detailed feedback. I tend to be bad about docs so I just wanted to point it out before I forgot. Thanks for giving me write perms. I have been working on a large project using Cassandra 1.2.0 (from the betas on up) with CQL, and this project really has a lot of stuff I have been looking for. Prior to making the switch to CQL, I was using Hector and it is fantastic library. Keep up the good work guys!
