### ISSUE TITLE
API: Java Client

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#7]
What does a modern Java API look like for this system? We should support:
- ORM (but optionally!)
- method chaining/guava style factories
- decomposition over inheritance
- column familes and keyspaces should be created automatically (like mongo collections and databases)

This should be as 1-2-3 as the MongoDB java client, but support the semantics of Guava and Firebrand.

**Comment by edwardcapriolo** [comment]
Where are we going with this one? As things have played out we have a very light java client, intravert has played out to be more of a transport then a client. A transport that is so "simple" you build your own "client". I do like firebrands approach with...

@ColumnFamily
@NamedQueries({
        @NamedQuery(name = Account.QUERY_ALL_ACCOUNTS_WITH_NAME, query = "select \* from Account where name = :name")
})
public class Account {

maybe we can adopt some annotations that map a series of intraop's to an object, but as its stands now, I am not sure typed operations and builder patterns are where we are going. Re-open if someone strongly wants to write a client
