### ISSUE TITLE
Cleanup on IntraClient

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#77]
- remove main method, move to test case where applicable
- remove sendBlocking method and return a future (potentially a Promise depending on the implementation in the 2.0 API).

**Comment by edwardcapriolo** [comment]
Take a look at #91 I used the countdown latch. (not futures) but I made the thing thread safe, and i benched it, just as fast over 25k inserts as ic1

**Comment by edwardcapriolo** [comment]
IC1 was deleted. ic2 is the only client left in the project.
