### ISSUE TITLE
I really do like IntraOp.Type but we need to get this code into seperate files

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#83]
I find myself Flipping through IntraOp quite often trying to find a spot in the code. Using Enum is nice for this but I think it really needs to break out into different classes. Maybe its me not being good with eclipse shortcuts but I find it really hard to find the place I want to work at this point.

**Comment by edwardcapriolo** [comment]
Nate, I put it on you since you have the best code organization sense.

**Comment by zznate** [comment]
Agreed - it was a good way to trim out the branching logic for optype initially, but we need to move each out into services classes.

**Comment by edwardcapriolo** [comment]
Async and class per handler has resolved this.
