### ISSUE TITLE
Update to tracking master (future 2.0) of vert.x 

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#85]
This is not ideal, but there are enough changes with things like multi-threaded worker verticles as well as promises API that we need to be on top of and will have significant design impact.

**Comment by zznate** [comment]
BETA of vert.x 2.0 is now available on maven central.

**Comment by edwardcapriolo** [comment]
I am only finding 1.3.X
http://mvnrepository.com/artifact/org.vert-x/vertx-platform

Please provide the info.

**Comment by zznate** [comment]
Closed in favor of #211
