### ISSUE TITLE
Prepared Statements

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#89]
Because the entire IntraReq is serializable it should be easy to store these in intravert memory. 

```
    IntraReq req = new IntraReq();
    req.add( Operations.slice("1",Operations.bindHere(1),"3") );
            req.add( Operations.storeReq() );  --> returns id like 12
```

  StoreReq would return an id to be used later.

IntraReq req = new IntraReq();
req.add( Operations.executeSTored(12, new map(12, "my value") );

**Comment by zznate** [comment]
Absolutely yes.

FYI - this is tangentially similar to how I was seeing GETREF as discussed on that previous issue, but in the context of a request envelope. We'll discuss more about that later.

Required for both I think will be sound naming/reference semantics.

**Comment by edwardcapriolo** [comment]
Just like getref this can be done with ServiceProcessor as well so maybe it is not worth doing.

**Comment by zznate** [comment]
From the perspective of 'stored functionality' I think it is definitely something we should support. 

What about pushing this concept a little further though. 
1. How much of the IntraReq could we store?
2. What would be a compact format to populate it?

The goal would be to save the overhead of passing the envelope every time for common operations. 

Thought?

**Comment by edwardcapriolo** [comment]
1) I think we can store the entire Intreq. We just pop off the store op.

2) 
req.add( Operations.slice("1",Operations.bindHere(1),"3") );  --> returns id (12)
bindHere would be an object like getref. We are saying, this is marker 1.

Then we populate it like this (I had a syntax error above):
req.add( Operations.executeSTored(12, new map(1, "my value") );

So the user sends the stored id and then the map of bind variables.

**Comment by zznate** [comment]
Adding a 'name' field to op in the JSON might make some of this a whole lot easier.

**Comment by edwardcapriolo** [comment]
I think it is the same issue really. You need to know the op id to set it or retrieve the results. 

Right now getOpRes.get(Integer) is how we fetch our results. We could make the results an ordering map. If the op does not have a user supplied name the implicit order of the op is used to as a key otherwise a user generated key.

This allows us to say req.add( Operations.getOp(4,5).set("id", "x") )

Then this can be retrived with
res.getOpRes().get("x")

The only subtle issues is if the user supplies a numeric id that clashes with the autogenerated ones., but that is a small edge case. I have been wanting to do this for a while anyway. So the change is op ids are now arbitrary objects but should be integers or strings. I will look at making this change. Probably open another ticket.

**Comment by edwardcapriolo** [comment]
WE did this as part of another issuel
